"""removed constraints

Revision ID: e1da6a88afea
Revises: 3d7d7adb64d5
Create Date: 2024-07-22 03:11:31.615604

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e1da6a88afea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.alter_column('brand',
                              existing_type=sa.VARCHAR(length=20),
                              nullable=True)
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=20),
                              nullable=True)
        batch_op.drop_index('ix_keys_name')
        batch_op.create_index(batch_op.f('ix_keys_name'), ['name'], unique=False)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dead', sa.Boolean(), nullable=True))
        batch_op.drop_index('ix_rooms_color')
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=10), nullable=True))
        batch_op.create_index('ix_rooms_color', ['color'], unique=False)
        batch_op.drop_column('dead')

    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keys_name'))
        batch_op.create_index('ix_keys_name', ['name'], unique=1)
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=20),
                              nullable=False)
        batch_op.alter_column('brand',
                              existing_type=sa.VARCHAR(length=20),
                              nullable=False)

    # ### end Alembic commands ###
